language: java
script: mvn clean install --fail-at-end
notifications:
  email:
    on_failure: true
matrix:
  include:
  - jdk: openjdk6
    env: JACOCO=true
  - jdk: openjdk7
    env: JACOCO=true COVERALLS=true
  - jdk: oraclejdk7
    env: JACOCO=true
  - jdk: oraclejdk8
    env: JACOCO=true
  - jdk: openjdk7
    env: JACOCO=true SONAR=publish
    script: mvn clean install sonar:sonar --fail-at-end
